require('dotenv').config()
module.exports={
  development:{
    client:"sqlite3",
    connection:{
      filename:process.env.SQLITE_FILENAME,
    },
    migrations:{
      directory:"./src/database/migrations"
  },
  useNullAsDefault:true,
  },
  test:{
    client:"sqlite3",
    connection:{
     filename:"./src/database/test.sqlite",
    },
    migrations:{
      directory:"./src/database/migrations"
  },
  useNullAsDefault:true,
    }
  }
